### ISSUE TITLE
Installing Grid as a stateless component installs old (empty?!) code

### ISSUE THREAD

**Issue by nicolechung** [twg/react-tools#16]
When I tried

```
trt generate sc Grid
```

I get:

```
import React from 'react'
import css from './style.css'

const Grid = () => (
  <div className={css.grid} />
)

Grid.propTypes = {
}

export default Grid
```

instead of the Grid component in src/Grid, e.g. https://github.com/twg/react-tools/tree/master/src/Grid

**Comment by hyperwidget** [comment]
`generate sc` is used to create a new stateless component

If you want to  the grid component from TRT you want `include Grid`

**Comment by nicolechung** [comment]
Ah!
