### ISSUE TITLE
Webpack, jest

### ISSUE THREAD

**Issue by nicolechung** [twg/react-tools#17]
Some of the components have jest tests but you can't actually run it from inside this repo.

Shall I lift some of our jest config(s) from other projects and place it into this project?

**Comment by hyperwidget** [comment]
hah; can you _not_? That's a bit of an oversight on my part; lolol - - yes, adding a jest config would be great

**Comment by spiderbites** [comment]
I have a "tests" branch that I started but never got to the PR stage

**Comment by nicolechung** [comment]
Yeah @spiderbites does that branch need the global `requestAnimationFrame` polyfill now that it's react-16? (I just ran into the same error today and copied your code)

**Comment by spiderbites** [comment]
yeah probably, i wrote that code pre-react16

**Comment by nicolechung** [comment]
Updated https://github.com/twg/react-tools/pull/18 with master and added a few tests and mocks.
