### ISSUE TITLE
Open source this project

### ISSUE THREAD

**Issue by derek-watson** [twg/react-tools#8]
Hello!

Before we go too far down the rabbit hole of privacy, let's open-source this work so that everything that goes into it is done through the lens of transparency and openness to external collaboration.

Here's a rough take:

- [x] Add `{ "license" : "MIT" }` to `package.json`
- [x] Create a `LICENSE` file in the root of the project with the MIT license text
- [x] Flip the GitHub repository to public
- [x] Publish to npm
- [x] Share the npm package with me and I'll merge it into our NPM org
- [x] Update README usage instructions 
- [x] 🎉

**Comment by hyperwidget** [comment]
🎉
